name: Log only when pushed

on:
  push:
    branches:
      - main

jobs:
  log-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show simple log
        run: |
          echo "✅ GitHub Actions workflow triggered!"
          echo "🕒 Timestamp: $(date)"
          echo "📦 Repository: ${{ github.repository }}"
          echo "👤 Triggered by: ${{ github.actor }}"
